### ISSUE TITLE
E-commerce Purchase Tag is only capturing one product from the eCommerce object items array

### ISSUE THREAD

**Issue by HebrewToYou** [braze-inc/braze-gtm-actions#11]
Steps to Reproduce:
1. Ensure a GTM `purchase` event is fired using the standard ecommerce json
2. Include two distinct purchases in the items array

Expected Result:
- Braze logs a purchase of both items for the user

Actual Result:
- Braze logs only a single purchase and it appears to be the second item in the array

`  ecommerce: {
    transaction_id: "pi_3OOlfDBM1hSKAOrN1JxDMZI7",
    value: "30.00",
    currency: "USD",
    items: [
      {
        item_id: 43,
        item_name: "Standard",
        item_category: "Service Plan",
        item_list_id: "acp_plans",
        item_list_name: "ACP Plans",
        price: "30.00",
        quantity: 1
      },
      {
        item_id: "sim",
        item_name: "SIM",
        index: 0,
        item_category: "Device",
        item_list_id: "acp_devices",
        item_list_name: "ACP Devices",
        price: "0.00",
        quantity: 1
      }
    ]
  }
}`

![image](https://github.com/braze-inc/braze-gtm-actions/assets/259987/4384cabc-31de-42ae-a830-834e2a2d3050)

![image](https://github.com/braze-inc/braze-gtm-actions/assets/259987/2d477559-a3dc-471d-a0ff-08ef560ea44a)

**Comment by davidbielik** [comment]
Hi @HebrewToYou I tried your code sample and see this error logged because your item name `43` is a number and not a string. Changing it to `"43"` (as a string) allows it to be logged as a product name in our SDK.

Before:
<img width="632" alt="image" src="https://github.com/braze-inc/braze-gtm-actions/assets/7410770/927cdd08-3067-46f2-b8c7-8ecb5746c01b">

After:
<img width="714" alt="image" src="https://github.com/braze-inc/braze-gtm-actions/assets/7410770/8416a06b-3aae-4ad2-a961-079a2bc23480">

According to [Google's events schema](https://developers.google.com/analytics/devguides/collection/ga4/reference/events?client_type=gtag#purchase_item), `item_id` is required to be a string.

Let me know if updating that field to a string still doesn't work and we can investigate this some more.

**Comment by HebrewToYou** [comment]
Thanks @davidbielik - that appears to be the issue. Thanks for identifying our problem and sorry for the erroneous issue.
