### ISSUE TITLE
Tag sequencing

### ISSUE THREAD

**Issue by mariusrudolph** [braze-inc/braze-gtm-actions#7]
Hi there,
At the moment our custom events which we would like to send to braze are only transferred to braze when we load the Braze Init tag before the actual event via the tag sequencing function within GTM.

<img width="673" alt="Bildschirmfoto 2022-08-11 um 17 50 17" src="https://user-images.githubusercontent.com/1136343/184175640-c2d43f2a-52bc-41b0-a51e-0065e439cadf.png">

If we do not load the Base tag before, the custom event is not pushed to braze. Do you know why? The Braze Base Init tag loads on every page_view so it doesn't seem correct to us that we need to load it again when pushing a custom event. 

Any help is as always highly appreciated.

**Comment by davidbielik** [comment]
Hi @mariusrudolph you might have to configure the tag's priority so that you guarantee the Initialization Tag fires _before_ your custom event.

If that doesn't fix it, please reach out to our Braze Support team (support@braze.com) and include steps to reproduce, verbose logs, and any other relevant screenshots or information.
